// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: championships_groups_stats.sql

package sqlc

import (
	"context"
)

const listGroupsStatsByYear = `-- name: ListGroupsStatsByYear :many
SELECT
    year,
    stage,
    group_code,
    team_code,
    matches_played,
    wins,
    draws,
    losses,
    goals_for,
    goals_against,
    goal_difference,
    points,
    unified_points,
    position
FROM championships_groups_stats
WHERE year = $1
ORDER BY stage, group_code, position
`

func (q *Queries) ListGroupsStatsByYear(ctx context.Context, year int32) ([]ChampionshipsGroupsStat, error) {
	rows, err := q.db.Query(ctx, listGroupsStatsByYear, year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChampionshipsGroupsStat
	for rows.Next() {
		var i ChampionshipsGroupsStat
		if err := rows.Scan(
			&i.Year,
			&i.Stage,
			&i.GroupCode,
			&i.TeamCode,
			&i.MatchesPlayed,
			&i.Wins,
			&i.Draws,
			&i.Losses,
			&i.GoalsFor,
			&i.GoalsAgainst,
			&i.GoalDifference,
			&i.Points,
			&i.UnifiedPoints,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
