// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: champion.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countChampions = `-- name: CountChampions :one
SELECT COUNT(1)
FROM (
    SELECT cs.champion_code
    FROM championships_stats cs
    GROUP BY cs.champion_code
) c
`

func (q *Queries) CountChampions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countChampions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listChampions = `-- name: ListChampions :many
SELECT
    c.champion_code AS team_code,
    t.name,
    c.wins,
    c.years
FROM (
    SELECT
        cs.champion_code,
        COUNT(1) AS wins,
        ARRAY_AGG(cs.year ORDER BY cs.year ASC)::integer[] AS years
    FROM championships_stats cs
    GROUP BY cs.champion_code
) c
INNER JOIN teams t ON t.code = c.champion_code
ORDER BY c.wins DESC, t.name ASC
LIMIT $1 OFFSET $2
`

type ListChampionsParams struct {
	Limit  int32
	Offset int32
}

type ListChampionsRow struct {
	TeamCode pgtype.Text
	Name     string
	Wins     int64
	Years    []int32
}

func (q *Queries) ListChampions(ctx context.Context, arg ListChampionsParams) ([]ListChampionsRow, error) {
	rows, err := q.db.Query(ctx, listChampions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChampionsRow
	for rows.Next() {
		var i ListChampionsRow
		if err := rows.Scan(
			&i.TeamCode,
			&i.Name,
			&i.Wins,
			&i.Years,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
