// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: championships_groups_stats.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listGroupsStatsByYear = `-- name: ListGroupsStatsByYear :many
SELECT
    championships_groups_stats.year,
    championships_groups_stats.stage::text AS stage,
    championships_groups_stats.group_code,
    championships_groups_stats.team_code,
    championships_groups_stats.matches_played,
    championships_groups_stats.wins,
    championships_groups_stats.draws,
    championships_groups_stats.losses,
    championships_groups_stats.goals_for,
    championships_groups_stats.goals_against,
    championships_groups_stats.goal_difference,
    championships_groups_stats.points,
    championships_groups_stats.unified_points,
    championships_groups_stats.position
FROM championships_groups_stats
WHERE year = $1
ORDER BY championships_groups_stats.stage, group_code, position
`

type ListGroupsStatsByYearRow struct {
	Year           int32
	Stage          string
	GroupCode      string
	TeamCode       string
	MatchesPlayed  int32
	Wins           int32
	Draws          int32
	Losses         int32
	GoalsFor       int32
	GoalsAgainst   int32
	GoalDifference pgtype.Int4
	Points         int32
	UnifiedPoints  int32
	Position       pgtype.Int4
}

func (q *Queries) ListGroupsStatsByYear(ctx context.Context, year int32) ([]ListGroupsStatsByYearRow, error) {
	rows, err := q.db.Query(ctx, listGroupsStatsByYear, year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupsStatsByYearRow
	for rows.Next() {
		var i ListGroupsStatsByYearRow
		if err := rows.Scan(
			&i.Year,
			&i.Stage,
			&i.GroupCode,
			&i.TeamCode,
			&i.MatchesPlayed,
			&i.Wins,
			&i.Draws,
			&i.Losses,
			&i.GoalsFor,
			&i.GoalsAgainst,
			&i.GoalDifference,
			&i.Points,
			&i.UnifiedPoints,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
