// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: championship.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countChampionshipScorersByYear = `-- name: CountChampionshipScorersByYear :one
SELECT COUNT(*)
FROM squads_stats ss
INNER JOIN players p ON p.id = ss.player_id
WHERE ss.year = $1
    AND ss.goals > 0
    AND (
        $2::text = ''
        OR LOWER(p.first_name) LIKE '%' || LOWER($2) || '%'
        OR LOWER(p.last_name) LIKE '%' || LOWER($2) || '%'
    )
    AND ($3::text = '' OR ss.team_code = $3)
`

type CountChampionshipScorersByYearParams struct {
	Year    int32
	Column2 string
	Column3 string
}

func (q *Queries) CountChampionshipScorersByYear(ctx context.Context, arg CountChampionshipScorersByYearParams) (int64, error) {
	row := q.db.QueryRow(ctx, countChampionshipScorersByYear, arg.Year, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countChampionshipSquadByYearAndTeam = `-- name: CountChampionshipSquadByYearAndTeam :one
SELECT COUNT(*)
FROM squads s
INNER JOIN players p ON s.player_id = p.id
WHERE s.year = $1
    AND s.team_code = $2
`

type CountChampionshipSquadByYearAndTeamParams struct {
	Year     int32
	TeamCode string
}

func (q *Queries) CountChampionshipSquadByYearAndTeam(ctx context.Context, arg CountChampionshipSquadByYearAndTeamParams) (int64, error) {
	row := q.db.QueryRow(ctx, countChampionshipSquadByYearAndTeam, arg.Year, arg.TeamCode)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countChampionshipStadiumsByYear = `-- name: CountChampionshipStadiumsByYear :one
SELECT COUNT(*)
FROM championships_stadiums_stats css
INNER JOIN stadiums s ON s.id = css.stadium_id
WHERE css.year = $1
    AND ($2::text = '' OR LOWER(s.name) LIKE '%' || LOWER($2) || '%')
`

type CountChampionshipStadiumsByYearParams struct {
	Year    int32
	Column2 string
}

func (q *Queries) CountChampionshipStadiumsByYear(ctx context.Context, arg CountChampionshipStadiumsByYearParams) (int64, error) {
	row := q.db.QueryRow(ctx, countChampionshipStadiumsByYear, arg.Year, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countChampionshipStandingsByYear = `-- name: CountChampionshipStandingsByYear :one
SELECT COUNT(*)
FROM championships_teams ct
INNER JOIN championships_teams_stats cts ON ct.year = cts.year AND ct.team_code = cts.team_code
INNER JOIN championships_stats cs ON cs.year = ct.year
WHERE ct.year = $1
`

func (q *Queries) CountChampionshipStandingsByYear(ctx context.Context, year int32) (int64, error) {
	row := q.db.QueryRow(ctx, countChampionshipStandingsByYear, year)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countChampionshipTeamsByYear = `-- name: CountChampionshipTeamsByYear :one
SELECT COUNT(*)
FROM championships_teams ct
INNER JOIN teams t ON t.code = ct.team_code
LEFT JOIN team_translations tt
    ON tt.team_code = t.code
    AND tt.language = $5
INNER JOIN championships_teams_stats cts ON ct.year = cts.year AND ct.team_code = cts.team_code
WHERE ct.year = $1
    AND ($2::text = '' OR LOWER(COALESCE(tt.name, t.name)) LIKE '%' || LOWER($2) || '%')
    AND ($3::text = '' OR t.confederation_code = $3)
    AND ($4::text = '' OR cts.group_code = $4)
`

type CountChampionshipTeamsByYearParams struct {
	Year     int32
	Column2  string
	Column3  string
	Column4  string
	Language string
}

func (q *Queries) CountChampionshipTeamsByYear(ctx context.Context, arg CountChampionshipTeamsByYearParams) (int64, error) {
	row := q.db.QueryRow(ctx, countChampionshipTeamsByYear,
		arg.Year,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Language,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countChampionshipTeamsByYearWithoutNameFilter = `-- name: CountChampionshipTeamsByYearWithoutNameFilter :one
SELECT COUNT(*)
FROM championships_teams ct
INNER JOIN teams t ON t.code = ct.team_code
INNER JOIN championships_teams_stats cts ON ct.year = cts.year AND ct.team_code = cts.team_code
WHERE ct.year = $1
    AND ($2::text = '' OR t.confederation_code = $2)
    AND ($3::text = '' OR cts.group_code = $3)
`

type CountChampionshipTeamsByYearWithoutNameFilterParams struct {
	Year    int32
	Column2 string
	Column3 string
}

func (q *Queries) CountChampionshipTeamsByYearWithoutNameFilter(ctx context.Context, arg CountChampionshipTeamsByYearWithoutNameFilterParams) (int64, error) {
	row := q.db.QueryRow(ctx, countChampionshipTeamsByYearWithoutNameFilter, arg.Year, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countChampionships = `-- name: CountChampionships :one
SELECT COUNT(*)
FROM championships c
WHERE
    ($1::integer = 0 OR c.year = $1)
    AND ($2::text = '' OR EXISTS (
        SELECT 1
        FROM teams t
        LEFT JOIN team_translations tt
            ON tt.team_code = t.code
            AND tt.language = $4
        WHERE t.code = ANY(c.host_codes)
          AND LOWER(COALESCE(tt.name, t.name)) LIKE '%' || LOWER($2) || '%'
    ))
    AND ($3::text = '' OR EXISTS (
        SELECT 1
        FROM teams t
        WHERE t.code = ANY(c.host_codes)
          AND LOWER(t.confederation_code) = LOWER($3)
    ))
`

type CountChampionshipsParams struct {
	Column1  int32
	Column2  string
	Column3  string
	Language string
}

func (q *Queries) CountChampionships(ctx context.Context, arg CountChampionshipsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countChampionships,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Language,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countChampionshipsWithoutHostFilter = `-- name: CountChampionshipsWithoutHostFilter :one
SELECT COUNT(*)
FROM championships c
WHERE
    ($1::integer = 0 OR c.year = $1)
    AND ($2::text = '' OR EXISTS (
        SELECT 1
        FROM teams t
        WHERE t.code = ANY(c.host_codes)
          AND LOWER(t.confederation_code) = LOWER($2)
    ))
`

type CountChampionshipsWithoutHostFilterParams struct {
	Column1 int32
	Column2 string
}

func (q *Queries) CountChampionshipsWithoutHostFilter(ctx context.Context, arg CountChampionshipsWithoutHostFilterParams) (int64, error) {
	row := q.db.QueryRow(ctx, countChampionshipsWithoutHostFilter, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getChampionshipByYear = `-- name: GetChampionshipByYear :one
SELECT 
    c.year,
    c.start_date,
    c.end_date,
    c.host_codes,
    c.confederation_codes,
    c.champion_code,
    s.total_teams,
    s.total_matches,
    s.total_stadiums,
    s.total_players,
    s.total_goals,
    s.champion_code AS stats_champion_code,
    s.runner_up_code AS stats_runner_up_code,
    s.third_place_code AS stats_third_place_code,
    s.fourth_place_code AS stats_fourth_place_code,
    s.top_scorer_ids,
    s.top_scorer_goals
FROM championships c
LEFT JOIN championships_stats s ON s.year = c.year
WHERE c.year = $1
`

type GetChampionshipByYearRow struct {
	Year                 int32
	StartDate            pgtype.Date
	EndDate              pgtype.Date
	HostCodes            []string
	ConfederationCodes   []string
	ChampionCode         pgtype.Text
	TotalTeams           pgtype.Int4
	TotalMatches         pgtype.Int4
	TotalStadiums        pgtype.Int4
	TotalPlayers         pgtype.Int4
	TotalGoals           pgtype.Int4
	StatsChampionCode    pgtype.Text
	StatsRunnerUpCode    pgtype.Text
	StatsThirdPlaceCode  pgtype.Text
	StatsFourthPlaceCode pgtype.Text
	TopScorerIds         []int64
	TopScorerGoals       pgtype.Int4
}

func (q *Queries) GetChampionshipByYear(ctx context.Context, year int32) (GetChampionshipByYearRow, error) {
	row := q.db.QueryRow(ctx, getChampionshipByYear, year)
	var i GetChampionshipByYearRow
	err := row.Scan(
		&i.Year,
		&i.StartDate,
		&i.EndDate,
		&i.HostCodes,
		&i.ConfederationCodes,
		&i.ChampionCode,
		&i.TotalTeams,
		&i.TotalMatches,
		&i.TotalStadiums,
		&i.TotalPlayers,
		&i.TotalGoals,
		&i.StatsChampionCode,
		&i.StatsRunnerUpCode,
		&i.StatsThirdPlaceCode,
		&i.StatsFourthPlaceCode,
		&i.TopScorerIds,
		&i.TopScorerGoals,
	)
	return i, err
}

const listChampionshipScorersByYear = `-- name: ListChampionshipScorersByYear :many
SELECT
    p.id AS player_id,
    TRIM(CONCAT_WS(' ', NULLIF(p.first_name, ''), NULLIF(p.last_name, '')))::text AS full_name,
    ss.team_code,
    ss.goals
FROM squads_stats ss
INNER JOIN players p ON p.id = ss.player_id
WHERE ss.year = $1
    AND ss.goals > 0
    AND (
        $2::text = ''
        OR LOWER(p.first_name) LIKE '%' || LOWER($2) || '%'
        OR LOWER(p.last_name) LIKE '%' || LOWER($2) || '%'
    )
    AND ($3::text = '' OR ss.team_code = $3)
ORDER BY ss.goals DESC, full_name ASC
LIMIT $5 OFFSET $4
`

type ListChampionshipScorersByYearParams struct {
	Year        int32
	Column2     string
	Column3     string
	OffsetValue int32
	LimitValue  int32
}

type ListChampionshipScorersByYearRow struct {
	PlayerID int64
	FullName string
	TeamCode string
	Goals    int32
}

func (q *Queries) ListChampionshipScorersByYear(ctx context.Context, arg ListChampionshipScorersByYearParams) ([]ListChampionshipScorersByYearRow, error) {
	rows, err := q.db.Query(ctx, listChampionshipScorersByYear,
		arg.Year,
		arg.Column2,
		arg.Column3,
		arg.OffsetValue,
		arg.LimitValue,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChampionshipScorersByYearRow
	for rows.Next() {
		var i ListChampionshipScorersByYearRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.FullName,
			&i.TeamCode,
			&i.Goals,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChampionshipSquadByYearAndTeam = `-- name: ListChampionshipSquadByYearAndTeam :many
SELECT
    p.id AS player_id,
    COALESCE(p.first_name, '')::text AS first_name,
    COALESCE(p.last_name, '')::text AS last_name,
    s.position,
    s.shirt_number
FROM squads s
INNER JOIN players p ON s.player_id = p.id
WHERE s.year = $1
    AND s.team_code = $2
ORDER BY s.position ASC, p.last_name ASC, p.first_name ASC, p.id ASC
LIMIT $4 OFFSET $3
`

type ListChampionshipSquadByYearAndTeamParams struct {
	Year        int32
	TeamCode    string
	OffsetValue int32
	LimitValue  int32
}

type ListChampionshipSquadByYearAndTeamRow struct {
	PlayerID    int64
	FirstName   string
	LastName    string
	Position    pgtype.Text
	ShirtNumber pgtype.Int4
}

func (q *Queries) ListChampionshipSquadByYearAndTeam(ctx context.Context, arg ListChampionshipSquadByYearAndTeamParams) ([]ListChampionshipSquadByYearAndTeamRow, error) {
	rows, err := q.db.Query(ctx, listChampionshipSquadByYearAndTeam,
		arg.Year,
		arg.TeamCode,
		arg.OffsetValue,
		arg.LimitValue,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChampionshipSquadByYearAndTeamRow
	for rows.Next() {
		var i ListChampionshipSquadByYearAndTeamRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.FirstName,
			&i.LastName,
			&i.Position,
			&i.ShirtNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChampionshipStadiumsByYear = `-- name: ListChampionshipStadiumsByYear :many
SELECT
    s.id,
    s.name,
    COALESCE(s.city_name, '')::text AS city_name,
    COALESCE(s.country, '')::text AS country_code,
    COALESCE(s.capacity, 0)::integer AS capacity,
    css.matches_played
FROM championships_stadiums_stats css
INNER JOIN stadiums s ON s.id = css.stadium_id
WHERE css.year = $1
    AND ($2::text = '' OR LOWER(s.name) LIKE '%' || LOWER($2) || '%')
ORDER BY css.matches_played DESC, s.name ASC
LIMIT $3 OFFSET $4
`

type ListChampionshipStadiumsByYearParams struct {
	Year    int32
	Column2 string
	Limit   int32
	Offset  int32
}

type ListChampionshipStadiumsByYearRow struct {
	ID            int64
	Name          string
	CityName      string
	CountryCode   string
	Capacity      int32
	MatchesPlayed int32
}

func (q *Queries) ListChampionshipStadiumsByYear(ctx context.Context, arg ListChampionshipStadiumsByYearParams) ([]ListChampionshipStadiumsByYearRow, error) {
	rows, err := q.db.Query(ctx, listChampionshipStadiumsByYear,
		arg.Year,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChampionshipStadiumsByYearRow
	for rows.Next() {
		var i ListChampionshipStadiumsByYearRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CityName,
			&i.CountryCode,
			&i.Capacity,
			&i.MatchesPlayed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChampionshipStandingsByYear = `-- name: ListChampionshipStandingsByYear :many
SELECT
    cts.team_code,
    COALESCE(cts.group_code, '')::text AS group_code,
    cts.matches_played,
    cts.wins,
    cts.draws,
    cts.losses,
    cts.goals_for,
    cts.goals_against,
    cts.goal_difference,
    cts.points,
    cts.unified_points,
    cts.position,
    COALESCE(CASE
        WHEN ct.team_code = cs.champion_code THEN 'champion'
        WHEN ct.team_code = cs.runner_up_code THEN 'runner_up'
        WHEN ct.team_code = cs.third_place_code THEN 'third_place'
        WHEN ct.team_code = cs.fourth_place_code THEN 'fourth_place'
        ELSE cts.stage_reached::text
    END, '')::text AS performance
FROM championships_teams ct
INNER JOIN championships_teams_stats cts ON ct.year = cts.year AND ct.team_code = cts.team_code
INNER JOIN championships_stats cs ON cs.year = ct.year
WHERE ct.year = $1
ORDER BY cts.position ASC, cts.stage_reached
LIMIT $2 OFFSET $3
`

type ListChampionshipStandingsByYearParams struct {
	Year   int32
	Limit  int32
	Offset int32
}

type ListChampionshipStandingsByYearRow struct {
	TeamCode       string
	GroupCode      string
	MatchesPlayed  int32
	Wins           int32
	Draws          int32
	Losses         int32
	GoalsFor       int32
	GoalsAgainst   int32
	GoalDifference pgtype.Int4
	Points         int32
	UnifiedPoints  int32
	Position       pgtype.Int4
	Performance    string
}

func (q *Queries) ListChampionshipStandingsByYear(ctx context.Context, arg ListChampionshipStandingsByYearParams) ([]ListChampionshipStandingsByYearRow, error) {
	rows, err := q.db.Query(ctx, listChampionshipStandingsByYear, arg.Year, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChampionshipStandingsByYearRow
	for rows.Next() {
		var i ListChampionshipStandingsByYearRow
		if err := rows.Scan(
			&i.TeamCode,
			&i.GroupCode,
			&i.MatchesPlayed,
			&i.Wins,
			&i.Draws,
			&i.Losses,
			&i.GoalsFor,
			&i.GoalsAgainst,
			&i.GoalDifference,
			&i.Points,
			&i.UnifiedPoints,
			&i.Position,
			&i.Performance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChampionshipTeamsByYear = `-- name: ListChampionshipTeamsByYear :many
SELECT
    ct.year,
    ct.team_code,
    t.confederation_code,
    cts.group_code,
    COALESCE(CASE
        WHEN ct.team_code = cs.champion_code THEN 'champion'
        WHEN ct.team_code = cs.runner_up_code THEN 'runner_up'
        WHEN ct.team_code = cs.third_place_code THEN 'third_place'
        WHEN ct.team_code = cs.fourth_place_code THEN 'fourth_place'
        ELSE cts.stage_reached::text
    END, '')::text AS stage_reached,
    COALESCE(m.managers, '')::text AS managers
FROM championships_teams ct
INNER JOIN teams t ON t.code = ct.team_code
LEFT JOIN team_translations tt
    ON tt.team_code = t.code
    AND tt.language = $7
INNER JOIN championships_teams_stats cts ON ct.year = cts.year AND ct.team_code = cts.team_code
INNER JOIN championships_stats cs ON cs.year = ct.year
LEFT JOIN (
    SELECT
        cm.team_code,
        string_agg(NULLIF(TRIM(CONCAT_WS(' ', NULLIF(m.first_name, ''), NULLIF(m.last_name, ''))), ''), ', ') AS managers
    FROM championships_managers cm
    INNER JOIN managers m ON cm.manager_id = m.id
    WHERE cm.year = $1
    GROUP BY cm.team_code
) m ON m.team_code = ct.team_code
WHERE ct.year = $1
    AND ($2::text = '' OR LOWER(COALESCE(tt.name, t.name)) LIKE '%' || LOWER($2) || '%')
    AND ($3::text = '' OR t.confederation_code = $3)
    AND ($4::text = '' OR cts.group_code = $4)
ORDER BY cts.position ASC, cts.stage_reached DESC
LIMIT $5 OFFSET $6
`

type ListChampionshipTeamsByYearParams struct {
	Year     int32
	Column2  string
	Column3  string
	Column4  string
	Limit    int32
	Offset   int32
	Language string
}

type ListChampionshipTeamsByYearRow struct {
	Year              int32
	TeamCode          string
	ConfederationCode string
	GroupCode         pgtype.Text
	StageReached      string
	Managers          string
}

func (q *Queries) ListChampionshipTeamsByYear(ctx context.Context, arg ListChampionshipTeamsByYearParams) ([]ListChampionshipTeamsByYearRow, error) {
	rows, err := q.db.Query(ctx, listChampionshipTeamsByYear,
		arg.Year,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
		arg.Language,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChampionshipTeamsByYearRow
	for rows.Next() {
		var i ListChampionshipTeamsByYearRow
		if err := rows.Scan(
			&i.Year,
			&i.TeamCode,
			&i.ConfederationCode,
			&i.GroupCode,
			&i.StageReached,
			&i.Managers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChampionshipTeamsByYearWithoutNameFilter = `-- name: ListChampionshipTeamsByYearWithoutNameFilter :many
SELECT
    ct.year,
    ct.team_code,
    t.confederation_code,
    cts.group_code,
    COALESCE(CASE
        WHEN ct.team_code = cs.champion_code THEN 'champion'
        WHEN ct.team_code = cs.runner_up_code THEN 'runner_up'
        WHEN ct.team_code = cs.third_place_code THEN 'third_place'
        WHEN ct.team_code = cs.fourth_place_code THEN 'fourth_place'
        ELSE cts.stage_reached::text
    END, '')::text AS stage_reached,
    COALESCE(m.managers, '')::text AS managers
FROM championships_teams ct
INNER JOIN teams t ON t.code = ct.team_code
INNER JOIN championships_teams_stats cts ON ct.year = cts.year AND ct.team_code = cts.team_code
INNER JOIN championships_stats cs ON cs.year = ct.year
LEFT JOIN (
    SELECT
        cm.team_code,
        string_agg(NULLIF(TRIM(CONCAT_WS(' ', NULLIF(m.first_name, ''), NULLIF(m.last_name, ''))), ''), ', ') AS managers
    FROM championships_managers cm
    INNER JOIN managers m ON cm.manager_id = m.id
    WHERE cm.year = $1
    GROUP BY cm.team_code
) m ON m.team_code = ct.team_code
WHERE ct.year = $1
    AND ($2::text = '' OR t.confederation_code = $2)
    AND ($3::text = '' OR cts.group_code = $3)
ORDER BY cts.position ASC, cts.stage_reached DESC
LIMIT $4 OFFSET $5
`

type ListChampionshipTeamsByYearWithoutNameFilterParams struct {
	Year    int32
	Column2 string
	Column3 string
	Limit   int32
	Offset  int32
}

type ListChampionshipTeamsByYearWithoutNameFilterRow struct {
	Year              int32
	TeamCode          string
	ConfederationCode string
	GroupCode         pgtype.Text
	StageReached      string
	Managers          string
}

func (q *Queries) ListChampionshipTeamsByYearWithoutNameFilter(ctx context.Context, arg ListChampionshipTeamsByYearWithoutNameFilterParams) ([]ListChampionshipTeamsByYearWithoutNameFilterRow, error) {
	rows, err := q.db.Query(ctx, listChampionshipTeamsByYearWithoutNameFilter,
		arg.Year,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChampionshipTeamsByYearWithoutNameFilterRow
	for rows.Next() {
		var i ListChampionshipTeamsByYearWithoutNameFilterRow
		if err := rows.Scan(
			&i.Year,
			&i.TeamCode,
			&i.ConfederationCode,
			&i.GroupCode,
			&i.StageReached,
			&i.Managers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChampionships = `-- name: ListChampionships :many
SELECT
    year,
    start_date,
    end_date,
    host_codes,
    confederation_codes,
    champion_code
FROM championships c
WHERE
    ($1::integer = 0 OR c.year = $1)
    AND ($2::text = '' OR EXISTS (
        SELECT 1
        FROM teams t
        LEFT JOIN team_translations tt
            ON tt.team_code = t.code
            AND tt.language = $6
        WHERE t.code = ANY(c.host_codes)
          AND LOWER(COALESCE(tt.name, t.name)) LIKE '%' || LOWER($2) || '%'
    ))
    AND ($3::text = '' OR EXISTS (
        SELECT 1
        FROM teams t
        WHERE t.code = ANY(c.host_codes)
          AND LOWER(t.confederation_code) = LOWER($3)
    ))
ORDER BY c.year ASC
LIMIT $4 OFFSET $5
`

type ListChampionshipsParams struct {
	Column1  int32
	Column2  string
	Column3  string
	Limit    int32
	Offset   int32
	Language string
}

type ListChampionshipsRow struct {
	Year               int32
	StartDate          pgtype.Date
	EndDate            pgtype.Date
	HostCodes          []string
	ConfederationCodes []string
	ChampionCode       pgtype.Text
}

func (q *Queries) ListChampionships(ctx context.Context, arg ListChampionshipsParams) ([]ListChampionshipsRow, error) {
	rows, err := q.db.Query(ctx, listChampionships,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
		arg.Language,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChampionshipsRow
	for rows.Next() {
		var i ListChampionshipsRow
		if err := rows.Scan(
			&i.Year,
			&i.StartDate,
			&i.EndDate,
			&i.HostCodes,
			&i.ConfederationCodes,
			&i.ChampionCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChampionshipsWithoutHostFilter = `-- name: ListChampionshipsWithoutHostFilter :many
SELECT
    year,
    start_date,
    end_date,
    host_codes,
    confederation_codes,
    champion_code
FROM championships c
WHERE
    ($1::integer = 0 OR c.year = $1)
    AND ($2::text = '' OR EXISTS (
        SELECT 1
        FROM teams t
        WHERE t.code = ANY(c.host_codes)
          AND LOWER(t.confederation_code) = LOWER($2)
    ))
ORDER BY c.year ASC
LIMIT $3 OFFSET $4
`

type ListChampionshipsWithoutHostFilterParams struct {
	Column1 int32
	Column2 string
	Limit   int32
	Offset  int32
}

type ListChampionshipsWithoutHostFilterRow struct {
	Year               int32
	StartDate          pgtype.Date
	EndDate            pgtype.Date
	HostCodes          []string
	ConfederationCodes []string
	ChampionCode       pgtype.Text
}

func (q *Queries) ListChampionshipsWithoutHostFilter(ctx context.Context, arg ListChampionshipsWithoutHostFilterParams) ([]ListChampionshipsWithoutHostFilterRow, error) {
	rows, err := q.db.Query(ctx, listChampionshipsWithoutHostFilter,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChampionshipsWithoutHostFilterRow
	for rows.Next() {
		var i ListChampionshipsWithoutHostFilterRow
		if err := rows.Scan(
			&i.Year,
			&i.StartDate,
			&i.EndDate,
			&i.HostCodes,
			&i.ConfederationCodes,
			&i.ChampionCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
