// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: championship.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countChampionships = `-- name: CountChampionships :one
SELECT COUNT(*)
FROM championships c
WHERE
    ($1::integer = 0 OR c.year = $1)
    AND ($2::text = '' OR EXISTS (
        SELECT 1
        FROM national_teams t
        WHERE t.code = ANY(c.host_nation_codes)
          AND LOWER(t.name) LIKE '%' || LOWER($2) || '%'
    ))
    AND ($3::text = '' OR EXISTS (
        SELECT 1
        FROM national_teams t
        WHERE t.code = ANY(c.host_nation_codes)
          AND LOWER(t.confederation_code) = LOWER($3)
    ))
`

type CountChampionshipsParams struct {
	Column1 int32
	Column2 string
	Column3 string
}

func (q *Queries) CountChampionships(ctx context.Context, arg CountChampionshipsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countChampionships, arg.Column1, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getChampionshipByYear = `-- name: GetChampionshipByYear :one
SELECT 
    c.id,
    c.year,
    c.start_date,
    c.end_date,
    c.host_nation_codes,
    c.champion_code,
    s.total_teams,
    s.total_matches,
    s.total_stadiums,
    s.total_players,
    s.total_goals,
    s.champion_code AS stats_champion_code,
    s.runner_up_code AS stats_runner_up_code,
    s.third_place_code AS stats_third_place_code,
    s.fourth_place_code AS stats_fourth_place_code,
    s.top_scorer_ids,
    s.top_scorer_goals
FROM championships c
LEFT JOIN championship_stats s ON s.id = c.id
WHERE c.year = $1
`

type GetChampionshipByYearRow struct {
	ID                   int64
	Year                 int32
	StartDate            pgtype.Date
	EndDate              pgtype.Date
	HostNationCodes      []string
	ChampionCode         pgtype.Text
	TotalTeams           pgtype.Int4
	TotalMatches         pgtype.Int4
	TotalStadiums        pgtype.Int4
	TotalPlayers         pgtype.Int4
	TotalGoals           pgtype.Int4
	StatsChampionCode    pgtype.Text
	StatsRunnerUpCode    pgtype.Text
	StatsThirdPlaceCode  pgtype.Text
	StatsFourthPlaceCode pgtype.Text
	TopScorerIds         []int64
	TopScorerGoals       pgtype.Int4
}

func (q *Queries) GetChampionshipByYear(ctx context.Context, year int32) (GetChampionshipByYearRow, error) {
	row := q.db.QueryRow(ctx, getChampionshipByYear, year)
	var i GetChampionshipByYearRow
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.StartDate,
		&i.EndDate,
		&i.HostNationCodes,
		&i.ChampionCode,
		&i.TotalTeams,
		&i.TotalMatches,
		&i.TotalStadiums,
		&i.TotalPlayers,
		&i.TotalGoals,
		&i.StatsChampionCode,
		&i.StatsRunnerUpCode,
		&i.StatsThirdPlaceCode,
		&i.StatsFourthPlaceCode,
		&i.TopScorerIds,
		&i.TopScorerGoals,
	)
	return i, err
}

const listChampionships = `-- name: ListChampionships :many
SELECT
    id,
    year,
    start_date,
    end_date,
    host_nation_codes,
    champion_code
FROM championships c
WHERE
    ($1::integer = 0 OR c.year = $1)
    AND ($2::text = '' OR EXISTS (
        SELECT 1
        FROM national_teams t
        WHERE t.code = ANY(c.host_nation_codes)
          AND LOWER(t.name) LIKE '%' || LOWER($2) || '%'
    ))
    AND ($3::text = '' OR EXISTS (
        SELECT 1
        FROM national_teams t
        WHERE t.code = ANY(c.host_nation_codes)
          AND LOWER(t.confederation_code) = LOWER($3)
    ))
ORDER BY c.year ASC
LIMIT $4 OFFSET $5
`

type ListChampionshipsParams struct {
	Column1 int32
	Column2 string
	Column3 string
	Limit   int32
	Offset  int32
}

func (q *Queries) ListChampionships(ctx context.Context, arg ListChampionshipsParams) ([]Championship, error) {
	rows, err := q.db.Query(ctx, listChampionships,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Championship
	for rows.Next() {
		var i Championship
		if err := rows.Scan(
			&i.ID,
			&i.Year,
			&i.StartDate,
			&i.EndDate,
			&i.HostNationCodes,
			&i.ChampionCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
