// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: championship.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countChampionshipTeamsByYear = `-- name: CountChampionshipTeamsByYear :one
SELECT COUNT(*)
FROM championships_teams ct
INNER JOIN teams t ON t.code = ct.team_code
INNER JOIN championships_teams_stats cts ON ct.year = cts.year AND ct.team_code = cts.team_code
WHERE ct.year = $1
    AND ($2::text = '' OR LOWER(t.name) LIKE '%' || LOWER($2) || '%')
    AND ($3::text = '' OR t.confederation_code = $3)
    AND ($4::text = '' OR cts.group_code = $4)
`

type CountChampionshipTeamsByYearParams struct {
	Year    int32
	Column2 string
	Column3 string
	Column4 string
}

func (q *Queries) CountChampionshipTeamsByYear(ctx context.Context, arg CountChampionshipTeamsByYearParams) (int64, error) {
	row := q.db.QueryRow(ctx, countChampionshipTeamsByYear,
		arg.Year,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countChampionships = `-- name: CountChampionships :one
SELECT COUNT(*)
FROM championships c
WHERE
    ($1::integer = 0 OR c.year = $1)
    AND ($2::text = '' OR EXISTS (
        SELECT 1
        FROM teams t
        WHERE t.code = ANY(c.host_codes)
          AND LOWER(t.name) LIKE '%' || LOWER($2) || '%'
    ))
    AND ($3::text = '' OR EXISTS (
        SELECT 1
        FROM teams t
        WHERE t.code = ANY(c.host_codes)
          AND LOWER(t.confederation_code) = LOWER($3)
    ))
`

type CountChampionshipsParams struct {
	Column1 int32
	Column2 string
	Column3 string
}

func (q *Queries) CountChampionships(ctx context.Context, arg CountChampionshipsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countChampionships, arg.Column1, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getChampionshipByYear = `-- name: GetChampionshipByYear :one
SELECT 
    c.year,
    c.start_date,
    c.end_date,
    c.host_codes,
    c.champion_code,
    s.total_teams,
    s.total_matches,
    s.total_stadiums,
    s.total_players,
    s.total_goals,
    s.champion_code AS stats_champion_code,
    s.runner_up_code AS stats_runner_up_code,
    s.third_place_code AS stats_third_place_code,
    s.fourth_place_code AS stats_fourth_place_code,
    s.top_scorer_ids,
    s.top_scorer_goals
FROM championships c
LEFT JOIN championships_stats s ON s.year = c.year
WHERE c.year = $1
`

type GetChampionshipByYearRow struct {
	Year                 int32
	StartDate            pgtype.Date
	EndDate              pgtype.Date
	HostCodes            []string
	ChampionCode         pgtype.Text
	TotalTeams           pgtype.Int4
	TotalMatches         pgtype.Int4
	TotalStadiums        pgtype.Int4
	TotalPlayers         pgtype.Int4
	TotalGoals           pgtype.Int4
	StatsChampionCode    pgtype.Text
	StatsRunnerUpCode    pgtype.Text
	StatsThirdPlaceCode  pgtype.Text
	StatsFourthPlaceCode pgtype.Text
	TopScorerIds         []int64
	TopScorerGoals       pgtype.Int4
}

func (q *Queries) GetChampionshipByYear(ctx context.Context, year int32) (GetChampionshipByYearRow, error) {
	row := q.db.QueryRow(ctx, getChampionshipByYear, year)
	var i GetChampionshipByYearRow
	err := row.Scan(
		&i.Year,
		&i.StartDate,
		&i.EndDate,
		&i.HostCodes,
		&i.ChampionCode,
		&i.TotalTeams,
		&i.TotalMatches,
		&i.TotalStadiums,
		&i.TotalPlayers,
		&i.TotalGoals,
		&i.StatsChampionCode,
		&i.StatsRunnerUpCode,
		&i.StatsThirdPlaceCode,
		&i.StatsFourthPlaceCode,
		&i.TopScorerIds,
		&i.TopScorerGoals,
	)
	return i, err
}

const listChampionshipTeamsByYear = `-- name: ListChampionshipTeamsByYear :many
SELECT
    ct.year,
    ct.team_code,
    t.confederation_code,
    cts.group_code,
    COALESCE(CASE
        WHEN ct.team_code = cs.champion_code THEN 'champion'
        WHEN ct.team_code = cs.runner_up_code THEN 'runner_up'
        WHEN ct.team_code = cs.third_place_code THEN 'third_place'
        WHEN ct.team_code = cs.fourth_place_code THEN 'fourth_place'
        ELSE cts.stage_reached::text
    END, '')::text AS stage_reached,
    COALESCE(m.managers, '')::text AS managers
FROM championships_teams ct
INNER JOIN teams t ON t.code = ct.team_code
INNER JOIN championships_teams_stats cts ON ct.year = cts.year AND ct.team_code = cts.team_code
INNER JOIN championships_stats cs ON cs.year = ct.year
LEFT JOIN (
    SELECT
        cm.team_code,
        string_agg(NULLIF(TRIM(CONCAT_WS(' ', NULLIF(m.first_name, ''), NULLIF(m.last_name, ''))), ''), ', ') AS managers
    FROM championships_managers cm
    INNER JOIN managers m ON cm.manager_id = m.id
    WHERE cm.year = $1
    GROUP BY cm.team_code
) m ON m.team_code = ct.team_code
WHERE ct.year = $1
    AND ($2::text = '' OR LOWER(t.name) LIKE '%' || LOWER($2) || '%')
    AND ($3::text = '' OR t.confederation_code = $3)
    AND ($4::text = '' OR cts.group_code = $4)
ORDER BY cts.position ASC, cts.stage_reached DESC
LIMIT $5 OFFSET $6
`

type ListChampionshipTeamsByYearParams struct {
	Year    int32
	Column2 string
	Column3 string
	Column4 string
	Limit   int32
	Offset  int32
}

type ListChampionshipTeamsByYearRow struct {
	Year              int32
	TeamCode          string
	ConfederationCode string
	GroupCode         pgtype.Text
	StageReached      string
	Managers          string
}

func (q *Queries) ListChampionshipTeamsByYear(ctx context.Context, arg ListChampionshipTeamsByYearParams) ([]ListChampionshipTeamsByYearRow, error) {
	rows, err := q.db.Query(ctx, listChampionshipTeamsByYear,
		arg.Year,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChampionshipTeamsByYearRow
	for rows.Next() {
		var i ListChampionshipTeamsByYearRow
		if err := rows.Scan(
			&i.Year,
			&i.TeamCode,
			&i.ConfederationCode,
			&i.GroupCode,
			&i.StageReached,
			&i.Managers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChampionships = `-- name: ListChampionships :many
SELECT
    year,
    start_date,
    end_date,
    host_codes,
    champion_code
FROM championships c
WHERE
    ($1::integer = 0 OR c.year = $1)
    AND ($2::text = '' OR EXISTS (
        SELECT 1
        FROM teams t
        WHERE t.code = ANY(c.host_codes)
          AND LOWER(t.name) LIKE '%' || LOWER($2) || '%'
    ))
    AND ($3::text = '' OR EXISTS (
        SELECT 1
        FROM teams t
        WHERE t.code = ANY(c.host_codes)
          AND LOWER(t.confederation_code) = LOWER($3)
    ))
ORDER BY c.year ASC
LIMIT $4 OFFSET $5
`

type ListChampionshipsParams struct {
	Column1 int32
	Column2 string
	Column3 string
	Limit   int32
	Offset  int32
}

func (q *Queries) ListChampionships(ctx context.Context, arg ListChampionshipsParams) ([]Championship, error) {
	rows, err := q.db.Query(ctx, listChampionships,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Championship
	for rows.Next() {
		var i Championship
		if err := rows.Scan(
			&i.Year,
			&i.StartDate,
			&i.EndDate,
			&i.HostCodes,
			&i.ChampionCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
