// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: champion.sql

package sqlc

import (
	"context"
)

const countChampions = `-- name: CountChampions :one
SELECT COUNT(1)
FROM (
    SELECT t.unified_code
    FROM championships_stats cs
    INNER JOIN teams t ON t.code = cs.champion_code
    GROUP BY t.unified_code
) c
`

func (q *Queries) CountChampions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countChampions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listChampions = `-- name: ListChampions :many
SELECT
    c.unified_code AS team_code,
    c.wins,
    c.years
FROM (
    SELECT
        t.unified_code,
        COUNT(1) AS wins,
        ARRAY_AGG(cs.year ORDER BY cs.year ASC)::integer[] AS years
    FROM championships_stats cs
    INNER JOIN teams t ON t.code = cs.champion_code
    GROUP BY t.unified_code
) c
ORDER BY c.wins DESC, c.unified_code ASC
LIMIT $2 OFFSET $1
`

type ListChampionsParams struct {
	OffsetValue int32
	LimitValue  int32
}

type ListChampionsRow struct {
	TeamCode string
	Wins     int64
	Years    []int32
}

func (q *Queries) ListChampions(ctx context.Context, arg ListChampionsParams) ([]ListChampionsRow, error) {
	rows, err := q.db.Query(ctx, listChampions, arg.OffsetValue, arg.LimitValue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChampionsRow
	for rows.Next() {
		var i ListChampionsRow
		if err := rows.Scan(&i.TeamCode, &i.Wins, &i.Years); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
