// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: confederation.sql

package sqlc

import (
	"context"
)

const getConfederation = `-- name: GetConfederation :one
SELECT id, code, name FROM confederations WHERE id = $1
`

func (q *Queries) GetConfederation(ctx context.Context, id int64) (Confederation, error) {
	row := q.db.QueryRow(ctx, getConfederation, id)
	var i Confederation
	err := row.Scan(&i.ID, &i.Code, &i.Name)
	return i, err
}

const listConfederations = `-- name: ListConfederations :many
SELECT id, code, name FROM confederations ORDER BY id
`

func (q *Queries) ListConfederations(ctx context.Context) ([]Confederation, error) {
	rows, err := q.db.Query(ctx, listConfederations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Confederation
	for rows.Next() {
		var i Confederation
		if err := rows.Scan(&i.ID, &i.Code, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
