// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: confederation.sql

package sqlc

import (
	"context"
)

const getConfederationByCode = `-- name: GetConfederationByCode :one
SELECT code, name FROM confederations WHERE lower(code) = lower($1)
`

func (q *Queries) GetConfederationByCode(ctx context.Context, lower string) (Confederation, error) {
	row := q.db.QueryRow(ctx, getConfederationByCode, lower)
	var i Confederation
	err := row.Scan(&i.Code, &i.Name)
	return i, err
}

const listConfederations = `-- name: ListConfederations :many
SELECT code, name FROM confederations ORDER BY code
`

func (q *Queries) ListConfederations(ctx context.Context) ([]Confederation, error) {
	rows, err := q.db.Query(ctx, listConfederations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Confederation
	for rows.Next() {
		var i Confederation
		if err := rows.Scan(&i.Code, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
