// Code generated by sqlc. DO NOT EDIT.
// source: confederation.sql

package sqlc

import (
	"context"
)

const listConfederations = `-- name: ListConfederations :many
SELECT id, code, name FROM confederations ORDER BY id
`

func (q *Queries) ListConfederations(ctx context.Context) ([]Confederation, error) {
	rows, err := q.db.Query(ctx, listConfederations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Confederation
	for rows.Next() {
		var i Confederation
		if err := rows.Scan(&i.ID, &i.Code, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConfederation = `-- name: GetConfederation :one
SELECT id, code, name FROM confederations WHERE id = $1
`

func (q *Queries) GetConfederation(ctx context.Context, id int64) (Confederation, error) {
	row := q.db.QueryRow(ctx, getConfederation, id)
	var i Confederation
	err := row.Scan(&i.ID, &i.Code, &i.Name)
	return i, err
}

const createConfederation = `-- name: CreateConfederation :one
INSERT INTO confederations (code, name) VALUES ($1, $2) RETURNING id, code, name
`

type CreateConfederationParams struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

func (q *Queries) CreateConfederation(ctx context.Context, arg CreateConfederationParams) (Confederation, error) {
	row := q.db.QueryRow(ctx, createConfederation, arg.Code, arg.Name)
	var i Confederation
	err := row.Scan(&i.ID, &i.Code, &i.Name)
	return i, err
}

const updateConfederation = `-- name: UpdateConfederation :one
UPDATE confederations SET code = $2, name = $3 WHERE id = $1 RETURNING id, code, name
`

type UpdateConfederationParams struct {
	ID   int64  `json:"id"`
	Code string `json:"code"`
	Name string `json:"name"`
}

func (q *Queries) UpdateConfederation(ctx context.Context, arg UpdateConfederationParams) (Confederation, error) {
	row := q.db.QueryRow(ctx, updateConfederation, arg.ID, arg.Code, arg.Name)
	var i Confederation
	err := row.Scan(&i.ID, &i.Code, &i.Name)
	return i, err
}

const deleteConfederation = `-- name: DeleteConfederation :exec
DELETE FROM confederations WHERE id = $1
`

func (q *Queries) DeleteConfederation(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteConfederation, id)
	return err
}
