// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: goal.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countGoalsByPlayer = `-- name: CountGoalsByPlayer :one
SELECT COUNT(*)
FROM goals g
INNER JOIN matches m ON g.match_id = m.id
WHERE g.player_id = $1
    AND g.own_goal = FALSE
    AND ($2::int = 0 OR g.year = $2)
`

type CountGoalsByPlayerParams struct {
	PlayerID pgtype.Int8
	Year     int32
}

func (q *Queries) CountGoalsByPlayer(ctx context.Context, arg CountGoalsByPlayerParams) (int64, error) {
	row := q.db.QueryRow(ctx, countGoalsByPlayer, arg.PlayerID, arg.Year)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listGoalsByPlayer = `-- name: ListGoalsByPlayer :many
SELECT
    g.year,
    c.host_codes,
    m.match_date,
    (CASE
        WHEN g.team_condition = 'home' THEN m.away_team_code
        ELSE m.home_team_code
    END)::text AS opponent_team_code,
    g.minute_regular,
    g.penalty,
    COALESCE(m.stage::text, '') AS stage
FROM goals g
INNER JOIN matches m ON g.match_id = m.id
INNER JOIN championships c ON c.year = g.year
WHERE g.player_id = $1
    AND g.own_goal = FALSE
    AND ($2::int = 0 OR g.year = $2)
ORDER BY m.match_date ASC NULLS LAST, g.minute_regular ASC, g.id ASC
LIMIT $4 OFFSET $3
`

type ListGoalsByPlayerParams struct {
	PlayerID    pgtype.Int8
	Year        int32
	OffsetValue int32
	LimitValue  int32
}

type ListGoalsByPlayerRow struct {
	Year             int32
	HostCodes        []string
	MatchDate        pgtype.Date
	OpponentTeamCode string
	MinuteRegular    int32
	Penalty          pgtype.Bool
	Stage            interface{}
}

func (q *Queries) ListGoalsByPlayer(ctx context.Context, arg ListGoalsByPlayerParams) ([]ListGoalsByPlayerRow, error) {
	rows, err := q.db.Query(ctx, listGoalsByPlayer,
		arg.PlayerID,
		arg.Year,
		arg.OffsetValue,
		arg.LimitValue,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGoalsByPlayerRow
	for rows.Next() {
		var i ListGoalsByPlayerRow
		if err := rows.Scan(
			&i.Year,
			&i.HostCodes,
			&i.MatchDate,
			&i.OpponentTeamCode,
			&i.MinuteRegular,
			&i.Penalty,
			&i.Stage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
