// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matches.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listMatchesByYear = `-- name: ListMatchesByYear :many
SELECT
    id,
    year,
    stage::text AS stage,
    stage_type::text AS stage_type,
    group_code,
    replayed,
    replay_of,
    match_date,
    match_time,
    stadium_id,
    home_team_code,
    COALESCE(htt.name, ht.name)::varchar AS home_team_name,
    away_team_code,
    COALESCE(att.name, at.name)::varchar AS away_team_name,
    home_team_score,
    away_team_score,
    extra_time,
    penalty_shootout,
    home_team_score_penalties,
    away_team_score_penalties,
    home_team_win,
    away_team_win,
    draw,
    ref_id
FROM matches
INNER JOIN teams ht ON ht.code = matches.home_team_code
INNER JOIN teams at ON at.code = matches.away_team_code
LEFT JOIN team_translations htt
    ON htt.team_code = ht.code
    AND htt.language = $2
LEFT JOIN team_translations att
    ON att.team_code = at.code
    AND att.language = $2
WHERE year = $1
ORDER BY matches.stage, group_code, match_date, match_time
`

type ListMatchesByYearParams struct {
	Year     int32
	Language string
}

type ListMatchesByYearRow struct {
	ID                     int64
	Year                   int32
	Stage                  string
	StageType              string
	GroupCode              pgtype.Text
	Replayed               bool
	ReplayOf               pgtype.Int8
	MatchDate              pgtype.Date
	MatchTime              pgtype.Time
	StadiumID              pgtype.Int8
	HomeTeamCode           string
	HomeTeamName           string
	AwayTeamCode           string
	AwayTeamName           string
	HomeTeamScore          pgtype.Int4
	AwayTeamScore          pgtype.Int4
	ExtraTime              bool
	PenaltyShootout        bool
	HomeTeamScorePenalties pgtype.Int4
	AwayTeamScorePenalties pgtype.Int4
	HomeTeamWin            pgtype.Bool
	AwayTeamWin            pgtype.Bool
	Draw                   pgtype.Bool
	RefID                  pgtype.Text
}

func (q *Queries) ListMatchesByYear(ctx context.Context, arg ListMatchesByYearParams) ([]ListMatchesByYearRow, error) {
	rows, err := q.db.Query(ctx, listMatchesByYear, arg.Year, arg.Language)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMatchesByYearRow
	for rows.Next() {
		var i ListMatchesByYearRow
		if err := rows.Scan(
			&i.ID,
			&i.Year,
			&i.Stage,
			&i.StageType,
			&i.GroupCode,
			&i.Replayed,
			&i.ReplayOf,
			&i.MatchDate,
			&i.MatchTime,
			&i.StadiumID,
			&i.HomeTeamCode,
			&i.HomeTeamName,
			&i.AwayTeamCode,
			&i.AwayTeamName,
			&i.HomeTeamScore,
			&i.AwayTeamScore,
			&i.ExtraTime,
			&i.PenaltyShootout,
			&i.HomeTeamScorePenalties,
			&i.AwayTeamScorePenalties,
			&i.HomeTeamWin,
			&i.AwayTeamWin,
			&i.Draw,
			&i.RefID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
