// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matches.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listMatchesByYear = `-- name: ListMatchesByYear :many
SELECT
    id,
    year,
    stage::text AS stage,
    stage_type::text AS stage_type,
    group_code,
    replayed,
    replay_of,
    match_date,
    match_time,
    stadium_id,
    home_team_code,
    away_team_code,
    home_team_score,
    away_team_score,
    extra_time,
    penalty_shootout,
    home_team_score_penalties,
    away_team_score_penalties,
    home_team_win,
    away_team_win,
    draw,
    ref_id
FROM matches
WHERE year = $1
ORDER BY matches.stage, group_code, match_date, match_time
`

type ListMatchesByYearRow struct {
	ID                     int64
	Year                   int32
	Stage                  string
	StageType              string
	GroupCode              pgtype.Text
	Replayed               bool
	ReplayOf               pgtype.Int8
	MatchDate              pgtype.Date
	MatchTime              pgtype.Time
	StadiumID              pgtype.Int8
	HomeTeamCode           string
	AwayTeamCode           string
	HomeTeamScore          pgtype.Int4
	AwayTeamScore          pgtype.Int4
	ExtraTime              bool
	PenaltyShootout        bool
	HomeTeamScorePenalties pgtype.Int4
	AwayTeamScorePenalties pgtype.Int4
	HomeTeamWin            pgtype.Bool
	AwayTeamWin            pgtype.Bool
	Draw                   pgtype.Bool
	RefID                  pgtype.Text
}

func (q *Queries) ListMatchesByYear(ctx context.Context, year int32) ([]ListMatchesByYearRow, error) {
	rows, err := q.db.Query(ctx, listMatchesByYear, year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMatchesByYearRow
	for rows.Next() {
		var i ListMatchesByYearRow
		if err := rows.Scan(
			&i.ID,
			&i.Year,
			&i.Stage,
			&i.StageType,
			&i.GroupCode,
			&i.Replayed,
			&i.ReplayOf,
			&i.MatchDate,
			&i.MatchTime,
			&i.StadiumID,
			&i.HomeTeamCode,
			&i.AwayTeamCode,
			&i.HomeTeamScore,
			&i.AwayTeamScore,
			&i.ExtraTime,
			&i.PenaltyShootout,
			&i.HomeTeamScorePenalties,
			&i.AwayTeamScorePenalties,
			&i.HomeTeamWin,
			&i.AwayTeamWin,
			&i.Draw,
			&i.RefID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
