// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Championship struct {
	Year         int32
	StartDate    pgtype.Date
	EndDate      pgtype.Date
	HostCodes    []string
	ChampionCode pgtype.Text
}

type ChampionshipsGroupsStat struct {
	Year           int32
	Stage          interface{}
	GroupCode      string
	TeamCode       string
	MatchesPlayed  int32
	Wins           int32
	Draws          int32
	Losses         int32
	GoalsFor       int32
	GoalsAgainst   int32
	GoalDifference pgtype.Int4
	Points         int32
	UnifiedPoints  int32
	Position       pgtype.Int4
}

type ChampionshipsStat struct {
	Year            int32
	TotalTeams      int32
	TotalMatches    int32
	TotalStadiums   int32
	TotalPlayers    int32
	TotalGoals      int32
	ChampionCode    pgtype.Text
	RunnerUpCode    pgtype.Text
	ThirdPlaceCode  pgtype.Text
	FourthPlaceCode pgtype.Text
	TopScorerIds    []int64
	TopScorerGoals  int32
}

type ChampionshipsTeam struct {
	Year     int32
	TeamCode string
}

type Confederation struct {
	Code string
	Name string
}

type Match struct {
	ID                     int64
	Year                   int32
	Stage                  interface{}
	GroupCode              pgtype.Text
	Replayed               bool
	ReplayOf               pgtype.Int8
	MatchDate              pgtype.Date
	MatchTime              pgtype.Time
	StadiumID              pgtype.Int8
	HomeTeamCode           string
	AwayTeamCode           string
	HomeTeamScore          pgtype.Int4
	AwayTeamScore          pgtype.Int4
	ExtraTime              bool
	PenaltyShootout        bool
	HomeTeamScorePenalties pgtype.Int4
	AwayTeamScorePenalties pgtype.Int4
	HomeTeamWin            pgtype.Bool
	AwayTeamWin            pgtype.Bool
	Draw                   pgtype.Bool
	RefID                  pgtype.Text
	StageType              interface{}
}

type Stadium struct {
	ID   int64
	Name string
}

type Team struct {
	Code              string
	Name              string
	DissolutionDate   pgtype.Date
	ConfederationCode string
	FederationName    string
	FederationCode    string
}
