// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Confederation struct {
	ID   int64
	Code string
	Name string
}

type NationalTeam struct {
	ID              int64
	Name            string
	Code            string
	DissolutionDate pgtype.Date
	ConfederationID int64
	FederationName  string
	FederationCode  string
}
