// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: national_team.sql

package sqlc

import (
	"context"
)

const countNationalTeams = `-- name: CountNationalTeams :one
SELECT COUNT(*)
FROM national_teams
WHERE
    ($1::text = '' OR LOWER(name) LIKE '%' || LOWER($1) || '%')
    AND ($2::bigint = 0 OR confederation_id = $2)
    AND ($3::text = '' OR LOWER(federation_name) LIKE '%' || LOWER($3) || '%')
    AND ($4::text = '' OR LOWER(federation_code) = LOWER($4))
    AND ($5::boolean OR dissolution_date IS NULL)
`

type CountNationalTeamsParams struct {
	Column1 string
	Column2 int64
	Column3 string
	Column4 string
	Column5 bool
}

func (q *Queries) CountNationalTeams(ctx context.Context, arg CountNationalTeamsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNationalTeams,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getNationalTeamByCode = `-- name: GetNationalTeamByCode :one
SELECT
    id,
    name,
    code,
    dissolution_date,
    confederation_id,
    federation_name,
    federation_code
FROM national_teams
WHERE LOWER(code) = LOWER($1)
`

func (q *Queries) GetNationalTeamByCode(ctx context.Context, lower string) (NationalTeam, error) {
	row := q.db.QueryRow(ctx, getNationalTeamByCode, lower)
	var i NationalTeam
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.DissolutionDate,
		&i.ConfederationID,
		&i.FederationName,
		&i.FederationCode,
	)
	return i, err
}

const getNationalTeamByID = `-- name: GetNationalTeamByID :one
SELECT
    id,
    name,
    code,
    dissolution_date,
    confederation_id,
    federation_name,
    federation_code
FROM national_teams
WHERE id = $1
`

func (q *Queries) GetNationalTeamByID(ctx context.Context, id int64) (NationalTeam, error) {
	row := q.db.QueryRow(ctx, getNationalTeamByID, id)
	var i NationalTeam
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.DissolutionDate,
		&i.ConfederationID,
		&i.FederationName,
		&i.FederationCode,
	)
	return i, err
}

const listNationalTeams = `-- name: ListNationalTeams :many
SELECT
    id,
    name,
    code,
    dissolution_date,
    confederation_id,
    federation_name,
    federation_code
FROM national_teams
WHERE
    ($1::text = '' OR LOWER(name) LIKE '%' || LOWER($1) || '%')
    AND ($2::bigint = 0 OR confederation_id = $2)
    AND ($3::text = '' OR LOWER(federation_name) LIKE '%' || LOWER($3) || '%')
    AND ($4::text = '' OR LOWER(federation_code) = LOWER($4))
    AND ($5::boolean OR dissolution_date IS NULL)
ORDER BY name ASC
LIMIT $6 OFFSET $7
`

type ListNationalTeamsParams struct {
	Column1 string
	Column2 int64
	Column3 string
	Column4 string
	Column5 bool
	Limit   int32
	Offset  int32
}

func (q *Queries) ListNationalTeams(ctx context.Context, arg ListNationalTeamsParams) ([]NationalTeam, error) {
	rows, err := q.db.Query(ctx, listNationalTeams,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NationalTeam
	for rows.Next() {
		var i NationalTeam
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.DissolutionDate,
			&i.ConfederationID,
			&i.FederationName,
			&i.FederationCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
