// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scorer.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countScorers = `-- name: CountScorers :one
SELECT COUNT(*)
FROM players_stats ps
INNER JOIN players p ON p.id = ps.id
INNER JOIN teams t ON cardinality(p.list_teams) > 0 AND p.list_teams[1] = t.code
WHERE ps.goals > 0
    AND (
        $1::text = ''
        OR LOWER(p.first_name) LIKE '%' || LOWER($1) || '%'
        OR LOWER(p.last_name) LIKE '%' || LOWER($1) || '%'
    )
    AND ($2::text = '' OR t.unified_code = $2)
    AND ($3::text = '' OR t.confederation_code = $3)
`

type CountScorersParams struct {
	Column1 string
	Column2 string
	Column3 string
}

func (q *Queries) CountScorers(ctx context.Context, arg CountScorersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countScorers, arg.Column1, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getScorerByPlayerID = `-- name: GetScorerByPlayerID :one
SELECT
    p.id,
    COALESCE(p.first_name, '')::text AS first_name,
    COALESCE(p.last_name, '')::text AS last_name,
    COALESCE(p.position::text, '') AS position,
    p.list_championships,
    p.list_teams
FROM players p
WHERE p.id = $1
`

type GetScorerByPlayerIDRow struct {
	ID                int64
	FirstName         string
	LastName          string
	Position          interface{}
	ListChampionships []int32
	ListTeams         []string
}

func (q *Queries) GetScorerByPlayerID(ctx context.Context, playerID int64) (GetScorerByPlayerIDRow, error) {
	row := q.db.QueryRow(ctx, getScorerByPlayerID, playerID)
	var i GetScorerByPlayerIDRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Position,
		&i.ListChampionships,
		&i.ListTeams,
	)
	return i, err
}

const listScorerGoalsByPlayer = `-- name: ListScorerGoalsByPlayer :many
SELECT
    g.year,
    c.host_codes,
    m.match_date,
    (CASE
        WHEN g.team_condition = 'home' THEN m.away_team_code
        ELSE m.home_team_code
    END)::text AS opponent_team_code,
    g.minute_regular,
    g.penalty,
    COALESCE(m.stage::text, '') AS stage
FROM goals g
INNER JOIN matches m ON g.match_id = m.id
INNER JOIN championships c ON c.year = g.year
WHERE g.player_id = $1
    AND g.own_goal = FALSE
ORDER BY m.match_date ASC NULLS LAST, g.minute_regular ASC, g.id ASC
`

type ListScorerGoalsByPlayerRow struct {
	Year             int32
	HostCodes        []string
	MatchDate        pgtype.Date
	OpponentTeamCode string
	MinuteRegular    int32
	Penalty          pgtype.Bool
	Stage            interface{}
}

func (q *Queries) ListScorerGoalsByPlayer(ctx context.Context, playerID pgtype.Int8) ([]ListScorerGoalsByPlayerRow, error) {
	rows, err := q.db.Query(ctx, listScorerGoalsByPlayer, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScorerGoalsByPlayerRow
	for rows.Next() {
		var i ListScorerGoalsByPlayerRow
		if err := rows.Scan(
			&i.Year,
			&i.HostCodes,
			&i.MatchDate,
			&i.OpponentTeamCode,
			&i.MinuteRegular,
			&i.Penalty,
			&i.Stage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScorers = `-- name: ListScorers :many
SELECT
    p.id AS player_id,
    TRIM(CONCAT_WS(' ', NULLIF(p.first_name, ''), NULLIF(p.last_name, '')))::text AS full_name,
    t.unified_code AS team_code,
    ps.goals,
    p.list_teams,
    t.confederation_code
FROM players_stats ps
INNER JOIN players p ON p.id = ps.id
INNER JOIN teams t ON cardinality(p.list_teams) > 0 AND p.list_teams[1] = t.code
WHERE ps.goals > 0
    AND (
        $1::text = ''
        OR LOWER(p.first_name) LIKE '%' || LOWER($1) || '%'
        OR LOWER(p.last_name) LIKE '%' || LOWER($1) || '%'
    )
    AND ($2::text = '' OR t.unified_code = $2)
    AND ($3::text = '' OR t.confederation_code = $3)
ORDER BY ps.goals DESC, full_name ASC
LIMIT $5 OFFSET $4
`

type ListScorersParams struct {
	Column1     string
	Column2     string
	Column3     string
	OffsetValue int32
	LimitValue  int32
}

type ListScorersRow struct {
	PlayerID          int64
	FullName          string
	TeamCode          string
	Goals             int32
	ListTeams         []string
	ConfederationCode string
}

func (q *Queries) ListScorers(ctx context.Context, arg ListScorersParams) ([]ListScorersRow, error) {
	rows, err := q.db.Query(ctx, listScorers,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.OffsetValue,
		arg.LimitValue,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScorersRow
	for rows.Next() {
		var i ListScorersRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.FullName,
			&i.TeamCode,
			&i.Goals,
			&i.ListTeams,
			&i.ConfederationCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
