// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scorer.sql

package sqlc

import (
	"context"
)

const countScorers = `-- name: CountScorers :one
SELECT COUNT(*)
FROM players_stats ps
INNER JOIN players p ON p.id = ps.id
INNER JOIN teams t ON cardinality(p.list_teams) > 0 AND p.list_teams[1] = t.code
WHERE ps.goals > 0
    AND (
        $1::text = ''
        OR LOWER(p.first_name) LIKE '%' || LOWER($1) || '%'
        OR LOWER(p.last_name) LIKE '%' || LOWER($1) || '%'
    )
    AND ($2::text = '' OR t.unified_code = $2)
    AND ($3::text = '' OR t.confederation_code = $3)
`

type CountScorersParams struct {
	Column1 string
	Column2 string
	Column3 string
}

func (q *Queries) CountScorers(ctx context.Context, arg CountScorersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countScorers, arg.Column1, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listScorers = `-- name: ListScorers :many
SELECT
    p.id AS player_id,
    TRIM(CONCAT_WS(' ', NULLIF(p.first_name, ''), NULLIF(p.last_name, '')))::text AS full_name,
    t.unified_code AS team_code,
    ps.goals,
    p.list_teams,
    t.confederation_code
FROM players_stats ps
INNER JOIN players p ON p.id = ps.id
INNER JOIN teams t ON cardinality(p.list_teams) > 0 AND p.list_teams[1] = t.code
WHERE ps.goals > 0
    AND (
        $1::text = ''
        OR LOWER(p.first_name) LIKE '%' || LOWER($1) || '%'
        OR LOWER(p.last_name) LIKE '%' || LOWER($1) || '%'
    )
    AND ($2::text = '' OR t.unified_code = $2)
    AND ($3::text = '' OR t.confederation_code = $3)
ORDER BY ps.goals DESC, full_name ASC
LIMIT $5 OFFSET $4
`

type ListScorersParams struct {
	Column1     string
	Column2     string
	Column3     string
	OffsetValue int32
	LimitValue  int32
}

type ListScorersRow struct {
	PlayerID          int64
	FullName          string
	TeamCode          string
	Goals             int32
	ListTeams         []string
	ConfederationCode string
}

func (q *Queries) ListScorers(ctx context.Context, arg ListScorersParams) ([]ListScorersRow, error) {
	rows, err := q.db.Query(ctx, listScorers,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.OffsetValue,
		arg.LimitValue,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScorersRow
	for rows.Next() {
		var i ListScorersRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.FullName,
			&i.TeamCode,
			&i.Goals,
			&i.ListTeams,
			&i.ConfederationCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
