// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: standing.sql

package sqlc

import (
	"context"
)

const countStandings = `-- name: CountStandings :one
SELECT COUNT(*)
FROM standings s
INNER JOIN teams t ON t.code = s.team_code
WHERE
    ($1::text = '' OR LOWER(t.name) LIKE '%' || LOWER($1) || '%')
    AND ($2::text = '' OR t.confederation_code = $2)
`

type CountStandingsParams struct {
	Column1 string
	Column2 string
}

func (q *Queries) CountStandings(ctx context.Context, arg CountStandingsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStandings, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listStandings = `-- name: ListStandings :many
SELECT
    s.team_code,
    t.name,
    s.matches_played,
    s.wins,
    s.draws,
    s.losses,
    s.goals_for,
    s.goals_against,
    s.goal_difference,
    s.points,
    s.unified_points,
    s.position,
    s.unified_position
FROM standings s
INNER JOIN teams t ON t.code = s.team_code
WHERE
    ($1::text = '' OR LOWER(t.name) LIKE '%' || LOWER($1) || '%')
    AND ($2::text = '' OR t.confederation_code = $2)
ORDER BY s.position ASC
LIMIT $3 OFFSET $4
`

type ListStandingsParams struct {
	Column1 string
	Column2 string
	Limit   int32
	Offset  int32
}

type ListStandingsRow struct {
	TeamCode        string
	Name            string
	MatchesPlayed   int32
	Wins            int32
	Draws           int32
	Losses          int32
	GoalsFor        int32
	GoalsAgainst    int32
	GoalDifference  int32
	Points          int32
	UnifiedPoints   int32
	Position        int32
	UnifiedPosition int32
}

func (q *Queries) ListStandings(ctx context.Context, arg ListStandingsParams) ([]ListStandingsRow, error) {
	rows, err := q.db.Query(ctx, listStandings,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStandingsRow
	for rows.Next() {
		var i ListStandingsRow
		if err := rows.Scan(
			&i.TeamCode,
			&i.Name,
			&i.MatchesPlayed,
			&i.Wins,
			&i.Draws,
			&i.Losses,
			&i.GoalsFor,
			&i.GoalsAgainst,
			&i.GoalDifference,
			&i.Points,
			&i.UnifiedPoints,
			&i.Position,
			&i.UnifiedPosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
