// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team.sql

package sqlc

import (
	"context"
)

const countTeams = `-- name: CountTeams :one
SELECT COUNT(*)
FROM teams
WHERE
    ($1::text = '' OR LOWER(name) LIKE '%' || LOWER($1) || '%')
    AND ($2::text = '' OR LOWER(confederation_code) = LOWER($2))
    AND ($3::text = '' OR LOWER(federation_name) LIKE '%' || LOWER($3) || '%')
    AND ($4::text = '' OR LOWER(federation_code) = LOWER($4))
    AND ($5::boolean OR dissolution_date IS NULL)
`

type CountTeamsParams struct {
	Column1 string
	Column2 string
	Column3 string
	Column4 string
	Column5 bool
}

func (q *Queries) CountTeams(ctx context.Context, arg CountTeamsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTeams,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTeamByCode = `-- name: GetTeamByCode :one
SELECT
    code,
    name,
    dissolution_date,
    confederation_code,
    federation_name,
    federation_code
FROM teams
WHERE LOWER(code) = LOWER($1)
`

func (q *Queries) GetTeamByCode(ctx context.Context, lower string) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByCode, lower)
	var i Team
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.DissolutionDate,
		&i.ConfederationCode,
		&i.FederationName,
		&i.FederationCode,
	)
	return i, err
}

const listTeams = `-- name: ListTeams :many
SELECT
    code,
    name,
    dissolution_date,
    confederation_code,
    federation_name,
    federation_code
FROM teams
WHERE
    ($1::text = '' OR LOWER(name) LIKE '%' || LOWER($1) || '%')
    AND ($2::text = '' OR LOWER(confederation_code) = LOWER($2))
    AND ($3::text = '' OR LOWER(federation_name) LIKE '%' || LOWER($3) || '%')
    AND ($4::text = '' OR LOWER(federation_code) = LOWER($4))
    AND ($5::boolean OR dissolution_date IS NULL)
ORDER BY name ASC
LIMIT $6 OFFSET $7
`

type ListTeamsParams struct {
	Column1 string
	Column2 string
	Column3 string
	Column4 string
	Column5 bool
	Limit   int32
	Offset  int32
}

func (q *Queries) ListTeams(ctx context.Context, arg ListTeamsParams) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeams,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.DissolutionDate,
			&i.ConfederationCode,
			&i.FederationName,
			&i.FederationCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
