// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTeams = `-- name: CountTeams :one
SELECT COUNT(*)
FROM teams t
LEFT JOIN team_translations tt
    ON tt.team_code = t.code
    AND tt.language = $1
WHERE
    ($2::text = '' OR LOWER(COALESCE(tt.name, t.name)) LIKE '%' || LOWER($2) || '%')
    AND ($3::text = '' OR LOWER(t.confederation_code) = LOWER($3))
    AND ($4::text = '' OR LOWER(t.federation_name) LIKE '%' || LOWER($4) || '%')
    AND ($5::text = '' OR LOWER(t.federation_code) = LOWER($5))
    AND ($6::boolean OR t.dissolution_date IS NULL)
`

type CountTeamsParams struct {
	Language          string
	NameFilter        string
	ConfederationCode string
	FederationName    string
	FederationCode    string
	IncludeDissolved  bool
}

func (q *Queries) CountTeams(ctx context.Context, arg CountTeamsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTeams,
		arg.Language,
		arg.NameFilter,
		arg.ConfederationCode,
		arg.FederationName,
		arg.FederationCode,
		arg.IncludeDissolved,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTeamByCode = `-- name: GetTeamByCode :one
SELECT
    t.code,
    COALESCE(tt.name, t.name)::varchar AS name,
    t.dissolution_date,
    t.confederation_code,
    t.federation_name,
    t.federation_code
FROM teams t
LEFT JOIN team_translations tt
    ON tt.team_code = t.code
    AND tt.language = $1
WHERE LOWER(t.code) = LOWER($2)
`

type GetTeamByCodeParams struct {
	Language string
	Code     string
}

type GetTeamByCodeRow struct {
	Code              string
	Name              string
	DissolutionDate   pgtype.Date
	ConfederationCode string
	FederationName    string
	FederationCode    string
}

func (q *Queries) GetTeamByCode(ctx context.Context, arg GetTeamByCodeParams) (GetTeamByCodeRow, error) {
	row := q.db.QueryRow(ctx, getTeamByCode, arg.Language, arg.Code)
	var i GetTeamByCodeRow
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.DissolutionDate,
		&i.ConfederationCode,
		&i.FederationName,
		&i.FederationCode,
	)
	return i, err
}

const listTeams = `-- name: ListTeams :many
SELECT
    t.code,
    COALESCE(tt.name, t.name)::varchar AS name,
    t.dissolution_date,
    t.confederation_code,
    t.federation_name,
    t.federation_code
FROM teams t
LEFT JOIN team_translations tt
    ON tt.team_code = t.code
    AND tt.language = $1
WHERE
    ($2::text = '' OR LOWER(COALESCE(tt.name, t.name)) LIKE '%' || LOWER($2) || '%')
    AND ($3::text = '' OR LOWER(t.confederation_code) = LOWER($3))
    AND ($4::text = '' OR LOWER(t.federation_name) LIKE '%' || LOWER($4) || '%')
    AND ($5::text = '' OR LOWER(t.federation_code) = LOWER($5))
    AND ($6::boolean OR t.dissolution_date IS NULL)
ORDER BY COALESCE(tt.name, t.name) ASC
LIMIT $8 OFFSET $7
`

type ListTeamsParams struct {
	Language          string
	NameFilter        string
	ConfederationCode string
	FederationName    string
	FederationCode    string
	IncludeDissolved  bool
	OffsetValue       int32
	LimitValue        int32
}

type ListTeamsRow struct {
	Code              string
	Name              string
	DissolutionDate   pgtype.Date
	ConfederationCode string
	FederationName    string
	FederationCode    string
}

func (q *Queries) ListTeams(ctx context.Context, arg ListTeamsParams) ([]ListTeamsRow, error) {
	rows, err := q.db.Query(ctx, listTeams,
		arg.Language,
		arg.NameFilter,
		arg.ConfederationCode,
		arg.FederationName,
		arg.FederationCode,
		arg.IncludeDissolved,
		arg.OffsetValue,
		arg.LimitValue,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamsRow
	for rows.Next() {
		var i ListTeamsRow
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.DissolutionDate,
			&i.ConfederationCode,
			&i.FederationName,
			&i.FederationCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
