// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team_translation.sql

package sqlc

import (
	"context"
)

const listTeamTranslations = `-- name: ListTeamTranslations :many
SELECT
    team_code,
    language,
    name
FROM team_translations
ORDER BY language ASC, team_code ASC
`

func (q *Queries) ListTeamTranslations(ctx context.Context) ([]TeamTranslation, error) {
	rows, err := q.db.Query(ctx, listTeamTranslations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeamTranslation
	for rows.Next() {
		var i TeamTranslation
		if err := rows.Scan(&i.TeamCode, &i.Language, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
